/*ZCS:1.0,5.0:
Information : Generated by ZK Studio Style Designer, compatible with ZK 3.5.2;
Don't edit any content between SEC and SEC_E comments.
*/<%@ taglib uri="http://www.zkoss.org/dsp/web/core" prefix="c" %>
.ksearch {
	width:200px;
	height:18px;
}
.ksearch_lst {
    background: url("../img/search.png") no-repeat scroll 0 0 white;
    padding: 2px 2px 2px 18px;
    height:18px;
}
.submenu{
	width:172px;
}

.kwordlist{
	width:123px;
}

.align-right {
	text-align: right;
}
.kh-textbox{
	height:28px;
}

.k-ver-bar{
	display: inline-block;
	width: 10px;
	overflow: visible;
}

.k-result-msg{
	color: #09924B;
}

.k-asterisk, .k-error{
	color: red;
	text-align: center;
}

.FooterDiv {
    font-size: 10px;
    height: 50px;
    margin: 5px auto 5px;
    text-align: center;
    width: 100%;
}

.footer_bg {
	background-image: url(../img/app/bg_footer1.png);
	background-position: right top;
	background-repeat: no-repeat;
	padding: 0 15px 0 0;
}

.footer_bg_version {
	background-image: url(../img/app/bg_footer_version.png);
	background-position: left top;
	background-repeat: no-repeat;
	padding: 0 15px 0px 30px;
}

.k-footer, .green{
	color: #09924B;
}
.green{
	font-size: 14px;
}

.k-footer-version{
	text-align: left;
	font-size: 11px;
	float:left;
	width:90px;
}

.k-footer-copyright{
	text-align: right;
}

.none-border{
	border: none;
}

.k-listfooter-left{
  	text-align: left;
  	font-weight: bold; 
  	padding: 5px 10px 5px 5px!important;
}

.k-listfooter-right{
  	text-align: right;
  	font-weight: bold; 
  	padding: 5px 10px 5px 5px!important;
}



.DateDiv {
	color: #666;
	white-space: nowrap;
	font-size: 10px;
	padding-top: 3px;
}

.MenuHeader{
	text-align: right;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-weight: bold;
	color: #F46F22;
	padding-top: 7px;
	text-decoration: none;
}



.k-logo{
	margin: 0 10px 0 0;
    
}

.k-label-b{
	font-weight: bold;
}

.myLabel{
	font-family: arial,sans-serif;
    font-size: 12px;
    //font-weight: bold;
    color: #636363;
    margin:25px 0 0 0;
}

.txtBox{
	width:350px;
	margin: 0 30px 0 0;
}

.k-login{
	padding:100px 24px 0 75px;
	//width:250px;
}

.k-forgot-psw{
	padding:40px 24px 0 60px;
	
}

.k-forgot{
	margin: 0 0 0 2px;
	color: #2281CF;
	cursor: pointer;
}

.k-forgot:hover{
	text-decoration: underline
}

.bg_login{
	background-image: url(../img/kbureau/bg_kBureau_v1.2.png);
	width:532px; 
	height:348px;
}

.k-login-btn{
	margin: 20px 0 20px 412px;
}

.k-forgot-btn{
	margin: 20px 0 20px 82px;
}

.k-link{
	color: #000080;
	font-weight: bold;
	cursor: pointer;
}

.k-line{
	width:370px;
	border-color: #A0A0A0;
}

.k-login-bg{
	background-image: url(../img/app/bg_footer_version.png);
	background-position: left top;
	background-repeat: no-repeat;
	padding: 22px 0 0 25px;
	margin: 50px 10px 10px 10px;
	font-weight: bold;
	color: #B1D4C5;
	font-size: 16px;
}

.k-login-key{
	background-image: url(../img/kbureau/Unlock-64.png);
	background-position: left top;
	background-repeat: no-repeat;
	padding: 10px 10px 50px 80px;
	font-weight: bold;
	//color: #B1D4C5;
	font-size: 16px;
}

.k-forgot-key{
	background-image: url(../img/kbureau/forgot.png);
	background-position: left top;
	background-repeat: no-repeat;
	padding: 10px 0 50px 40px;
	font-weight: bold;
	//color: #B1D4C5;
	font-size: 16px;
}

.forgot-instr{
	margin: 20px 20px 0 0;
}

.errormsg {
  color:#DD4B39;
  display:block;
  line-height:17px;
  margin: 0 0 0 2px;
  //margin-bottom:0;
  //margin-left:0;
  //margin-right:0;
  //margin-top:0.5em;
  //padding: 0 10px 0 28px;
}

#reglang_box {
	height: 26px;
	float: right;
	margin-right: 10px;
	font-size: 10px;
	color: #109550;
}

#reglang_box .item {
    margin-right: 1px;
    padding: 3px 0 5px;
}

.item {
    font-size: 10px;
}

#reglang_box .username {
    max-width: 200px;
    overflow: hidden;
    text-align: right;
    padding-top:10px;
}

#reglang_box a {
    font-size: 10px;
}

.login_label{
	margin-bottom: -10px;
}

.tbl_util{
	width: 99%;
	padding: 0 10px 0 5px;
}

.k-hr{
	position: relative;
	top: 8px;
	border: 1px solid 
	#C5C5C5;
	border-bottom: none;
	border-left: none;
	border-right: none;
}

.k-version{
	float: right;
    margin-right: 15px;
    margin-top: -12px;
    color: #009600;
}

.support-bg{
	background-image: url(../img/kbureau/cheer.png);
	background-position: center top;
	background-repeat: no-repeat;
	padding: 0 0 0 20px;
	font-weight: bold;
	height: 500px;
}

.about-bg {
	background-image: url(../img/kbureau/kplus_bg.png);
	width: 532px;
	height: 348px;
}

#suport_content p, #suport_content ul li{
	font-size: 16px;
}

.about-logo{
	margin-top: -35px;
	margin-left: -10px;
}

.k-about-msg {
	color: #636363;
	font-family: arial, sans-serif;
	font-size: 16px;
}

#sub-menu tr{
	-moz-box-sizing: border-box;
    border-bottom: 1px solid #EBEAEA;
    border-top: 1px solid white;
    box-shadow: 0 1px 0 #FFFFFF;
    color: #3F3F3F;
    float: left;
    font-size: 14px;
    /*
    height: 38px;
    line-height: 38px;
    */
    position: relative;
    width: 100%;
}


/*************** Override ZK ****************/
.z-west-header, .z-center-header, .z-east-header, .z-north-header, .z-south-header{
	background: none repeat scroll 0 0 #F7F7F7!important;
}

.demo-header .z-north-body {
	/*background: url("../img/main_menubar_bg.png") repeat-x scroll 0 0 transparent!important;*/
	background: none repeat scroll 0 0 #F7F7F7!important;
}

h3.head {
    color: #333333;
    font-size: 18px;
    font-weight: bold;
    margin: 0;
    padding-top: 26px;
    font-family: Georgia;
    
}

table h3.head {
    color: #333333;
    font-size: 18px;
    font-weight: bold;
    margin: 0;
    padding-top: 20px;
    font-family: Georgia;
    
}

table h5.head, head5 {
    color: #333333;
    font-size: 14px!important;
    font-weight: normal!important;
    margin: 0;
    padding-top: 20px;
    font-family: Georgia!important;
    
}

.h-ruler{
	border-top: 1px dotted #C2C9BA;
	margin-top: 5px;
	
}

.header-border-div {
    border-bottom: 1px solid #FAFBFC;
    border-top: 1px solid #F18811;
    height: 0;
    width: 100%;
}

.content{
	padding: 0 10px 10px 10px;
}

#period_detail .cell-input {
	padding:0 0 0 15px;
}

#obs_detail .cell-input {
	padding:0 10px 0 15px;
}

#obs_detail .cell-input-area {
	padding:0 15px 0 15px;
}

#period_detail .cell-input-right {
	padding:0 20px 0 0;
}

.k-space{
	padding-top:10px;
}

#dict .k-space {
    padding-top: 4px;
}

#news .k-space {
    padding-left: 4px;
}
#dict img{
    border: 0 none;
    margin: 5px 3px 0 0;
}
