package org.jasper;

/*
 * JasperReports - Free Java Reporting Library.
 * Copyright (C) 2001 - 2011 Jaspersoft Corporation. All rights reserved.
 * http://www.jaspersoft.com
 *
 * Unless you have purchased a commercial license agreement from Jaspersoft,
 * the following license terms apply:
 *
 * This program is part of JasperReports.
 *
 * JasperReports is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JasperReports is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with JasperReports. If not, see <http://www.gnu.org/licenses/>.
 */
import java.awt.BorderLayout;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;

import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 * @author Teodor Danciu (teodord@users.sourceforge.net)
 * @version $Id: EmbeddedViewerApplet.java 5180 2012-03-29 13:23:12Z teodord $
 */
public class EmbeddedViewerApplet extends javax.swing.JApplet {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	static final String JDBC_DRIVER_JTDS = "net.sourceforge.jtds.jdbc.Driver";
	static final String USER = "sa";
	static final String PWD ="@HelloK12";
	static final String SERVER = "localhost";
	static final String KBUREAU_CONNECTION_STRING_JTDS = "jdbc:jtds:sqlserver://"+ SERVER +":1433/kBureau2;instance=db";
	
	/**
	 * 
	 * @return connection object
	 */
	public Connection getConnection() {
		Connection con = null;
		try {
			Class.forName(JDBC_DRIVER_JTDS);
			con = DriverManager.getConnection(KBUREAU_CONNECTION_STRING_JTDS, USER,
					PWD);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return con;
	}
	
	/**
	 *
	 */
	private JasperPrint jasperPrint;

	/** Creates new form AppletViewer */
	public EmbeddedViewerApplet() {
		initComponents();
	}
	
	

	/**
	*
	*/
	public void init() {
		try {
			System.out.println("Starting...");
			String url = "D:\\DOCUMENTS\\Projects\\kBureauPlus\\WebContent\\rpt\\test.jasper";
			Connection conn = getConnection();
			jasperPrint = (JasperPrint)JRLoader.loadObjectFromFile(url);
			conn.close();
			if (jasperPrint != null) {
				JRViewerSimple viewer = new JRViewerSimple(jasperPrint);
				this.pnlMain.add(viewer, BorderLayout.CENTER);
			}
		} catch (Exception e) {
			e.printStackTrace();

			StringWriter swriter = new StringWriter();
			PrintWriter pwriter = new PrintWriter(swriter);
			e.printStackTrace(pwriter);
			JOptionPane.showMessageDialog(this, swriter.toString());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		pnlMain = new javax.swing.JPanel();

		pnlMain.setLayout(new java.awt.BorderLayout());

		getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

	}// GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel pnlMain;
	// End of variables declaration//GEN-END:variables

}
