//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.15 at 06:18:22 PM ICT 
//


package kredit.web.kbureau.model.enquiry.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kredit.web.kbureau.model.enquiry.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kredit.web.kbureau.model.enquiry.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link REQUEST }
     * 
     */
    public REQUEST createREQUEST() {
        return new REQUEST();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE }
     * 
     */
    public REQUEST.MESSAGE createREQUESTMESSAGE() {
        return new REQUEST.MESSAGE();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY createREQUESTMESSAGEENQUIRY() {
        return new REQUEST.MESSAGE.ENQUIRY();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER createREQUESTMESSAGEENQUIRYCONSUMER() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CEMP }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CEMP createREQUESTMESSAGEENQUIRYCONSUMERCEMP() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CEMP();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM createREQUESTMESSAGEENQUIRYCONSUMERCNAM() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link REQUEST.HEADER }
     * 
     */
    public REQUEST.HEADER createREQUESTHEADER() {
        return new REQUEST.HEADER();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CID }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CID createREQUESTMESSAGEENQUIRYCONSUMERCID() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CID();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CDOB }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CDOB createREQUESTMESSAGEENQUIRYCONSUMERCDOB() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CDOB();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CPLB }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CPLB createREQUESTMESSAGEENQUIRYCONSUMERCPLB() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CPLB();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CADR }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CADR createREQUESTMESSAGEENQUIRYCONSUMERCADR() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CADR();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CCNT }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CCNT createREQUESTMESSAGEENQUIRYCONSUMERCCNT() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CCNT();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CEMP.EADR }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CEMP.EADR createREQUESTMESSAGEENQUIRYCONSUMERCEMPEADR() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CEMP.EADR();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM.CNMFA }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM.CNMFA createREQUESTMESSAGEENQUIRYCONSUMERCNAMCNMFA() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM.CNMFA();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM.CNM1A }
     * 
     */
    public REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM.CNM1A createREQUESTMESSAGEENQUIRYCONSUMERCNAMCNM1A() {
        return new REQUEST.MESSAGE.ENQUIRY.CONSUMER.CNAM.CNM1A();
    }

}
