
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BookmarkRole](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleCode] [varchar](3) NOT NULL,
	[BookmarkCode] [varchar](3) NOT NULL,
	[C] [int] NOT NULL,
	[R] [int] NOT NULL,
	[U] [int] NOT NULL,
	[D] [int] NOT NULL,
 CONSTRAINT [PK_UserAuthenBookmark] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
